export const KEYWORD_TOPIC_MAP: Record<string, string> = {
  'SELECT': 'sql-basics',
  'FROM': 'sql-basics',
  'WHERE': 'sql-basics',
  'LIMIT': 'sql-basics',
  'AND': 'filtering',
  'OR': 'filtering',
  'IN': 'filtering',
  'BETWEEN': 'filtering',
  'LIKE': 'filtering',
  'IS': 'filtering',
  'NOT': 'filtering',
  'NULL': 'filtering',
  'ORDER BY': 'sorting',
  'ASC': 'sorting',
  'DESC': 'sorting',
  'DISTINCT': 'sorting',
  'JOIN': 'joins',
  'INNER JOIN': 'joins',
  'LEFT JOIN': 'joins',
  'RIGHT JOIN': 'joins',
  'CROSS JOIN': 'joins',
  'ON': 'joins',
  'GROUP BY': 'aggregation',
  'HAVING': 'aggregation',
  'COUNT': 'aggregation',
  'SUM': 'aggregation',
  'AVG': 'aggregation',
  'MIN': 'aggregation',
  'MAX': 'aggregation',
  'UNION': 'set-operations',
  'INTERSECT': 'set-operations',
  'EXCEPT': 'set-operations',
  'INSERT': 'insert',
  'INTO': 'insert',
  'VALUES': 'insert',
  'UPDATE': 'update',
  'SET': 'update',
  'DELETE': 'delete',
  'CREATE TABLE': 'create-table',
  'PRIMARY KEY': 'constraints',
  'FOREIGN KEY': 'constraints',
  'NOT NULL': 'constraints',
  'UNIQUE': 'constraints',
  'ALTER TABLE': 'alter-table',
  'INDEX': 'indexes',
  'CREATE INDEX': 'indexes',
  'VIEW': 'views',
  'TRIGGER': 'triggers',
  'WITH': 'cte',
  'OVER': 'window-functions',
  'PARTITION BY': 'window-functions',
  'ROW_NUMBER': 'window-functions',
  'RANK': 'window-functions',
  'EXPLAIN': 'query-planning',
};

export const TOPIC_LABELS: Record<string, string> = {
  'sql-basics': 'SQL 基础查询',
  'filtering': '条件过滤',
  'sorting': '排序与去重',
  'joins': 'JOIN 查询',
  'aggregation': '聚合查询',
  'subqueries': '子查询',
  'set-operations': '集合操作',
  'insert': 'INSERT 插入',
  'update': 'UPDATE 更新',
  'delete': 'DELETE 删除',
  'create-table': 'CREATE TABLE',
  'constraints': '表约束',
  'alter-table': 'ALTER TABLE',
  'indexes': '索引',
  'views': '视图',
  'triggers': '触发器',
  'window-functions': '窗口函数',
  'cte': 'CTE 公共表表达式',
  'query-planning': '查询计划分析',
  'optimization': '查询优化',
  'data-types': 'SQLite 数据类型',
  'string-functions': '字符串函数',
  'datetime': '日期与时间函数',
  'transactions': '事务处理',
};

export const TOPIC_DIFFICULTY: Record<string, number> = {
  'sql-basics': 1, 'filtering': 1, 'sorting': 1, 'data-types': 1, 'string-functions': 1,
  'joins': 2, 'aggregation': 2, 'subqueries': 2, 'set-operations': 2, 'alter-table': 2,
  'indexes': 2, 'datetime': 2, 'views': 2, 'transactions': 2,
  'triggers': 3, 'window-functions': 3, 'cte': 3, 'query-planning': 3, 'optimization': 3,
  'insert': 1, 'update': 1, 'delete': 1, 'create-table': 1, 'constraints': 1,
};

export const DIFF_LABELS: Record<number, string> = { 1: '基础', 2: '进阶', 3: '高级' };

export const NEXT_TOPICS: Record<string, string[]> = {
  'sql-basics': ['filtering', 'sorting'],
  'filtering': ['aggregation', 'joins'],
  'sorting': ['aggregation', 'joins'],
  'joins': ['subqueries', 'aggregation'],
  'aggregation': ['subqueries', 'window-functions'],
  'subqueries': ['cte', 'window-functions'],
  'set-operations': ['cte', 'views'],
  'insert': ['update', 'delete'],
  'update': ['delete', 'transactions'],
  'delete': ['transactions', 'triggers'],
  'create-table': ['constraints', 'insert'],
  'constraints': ['joins', 'indexes'],
  'alter-table': ['indexes'],
  'indexes': ['query-planning', 'optimization'],
  'views': ['triggers'],
  'triggers': ['window-functions'],
  'window-functions': ['cte'],
  'cte': ['query-planning'],
  'query-planning': ['optimization'],
};
